### ISSUE TITLE
Contextual fragments refactoring

### ISSUE THREAD

**Issue by trofimovama** [trofimovama/way-to-middle#16]
### Details: 

To refactor the App using 
```javascript
document
  .createRange()
  .createContextualFragment()
```

Replace dynamically created Elements with fragments of a document containing nodes in components of the app.

**Comment by vladlen-volkov** [comment]
Example: [codepen](https://codepen.io/Vladlen-Volkov/pen/gOQgwrj)

**Comment by vladlen-volkov** [comment]
Btw, wouldn't it be better to wrap the code in the description in some custom function? Like `renderTemplate(htmlStr)`. 

It would solve two potential problems:
1. I case you decide to go with another API to render html fragments, it can be easily replaced in one place, not across entire code base.
2. It is a bit shorter then the whole chain of calling `document.createRange().createContextualFragment()`

It's only a suggestion, not a requirement, so it's up to you to decide whether you need it or not 😉
I case you decide to make the function you can put in a new folder `utils`.
