### ISSUE TITLE
Improving UX on the input

### ISSUE THREAD

**Issue by vladlen-volkov** [trofimovama/way-to-middle#6]
### Details:

We're going to slightly improve UX by adding familiar behavior to UI. 
Within this ticket it is suggested to add keyboard-specific event on our input:

![image](https://github.com/trofimovama/way-to-middle/assets/21365832/52d28ede-d2f1-4b01-a385-1fd3898db584)

 
Check out the [Article: keyboard events](https://learn.javascript.ru/keyboard-events), it may be helpful.

"Enter" - to add new item with the given content to our list;
"Esc" - clean the input completely.

#### Before get started:

Answer the question in the comments bellow:
What type of event will you choose to crack our case - "keydown" or "keyup"? Why?

**Comment by trofimovama** [comment]
I suppose that I will choose "keydown" event with "event.repeat" property set to "false"
